# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import unsloth_pb2 as unsloth__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in unsloth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UnslothModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/unsloth.UnslothModelService/Generate',
                request_serializer=unsloth__pb2.GenerateRequest.SerializeToString,
                response_deserializer=unsloth__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.Init = channel.unary_unary(
                '/unsloth.UnslothModelService/Init',
                request_serializer=unsloth__pb2.InitRequest.SerializeToString,
                response_deserializer=unsloth__pb2.InitResponse.FromString,
                _registered_method=True)
        self.UnloadLLM = channel.unary_unary(
                '/unsloth.UnslothModelService/UnloadLLM',
                request_serializer=unsloth__pb2.UnloadLLMRequest.SerializeToString,
                response_deserializer=unsloth__pb2.UnloadLLMResponse.FromString,
                _registered_method=True)


class UnslothModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadLLM(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnslothModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=unsloth__pb2.GenerateRequest.FromString,
                    response_serializer=unsloth__pb2.GenerateResponse.SerializeToString,
            ),
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=unsloth__pb2.InitRequest.FromString,
                    response_serializer=unsloth__pb2.InitResponse.SerializeToString,
            ),
            'UnloadLLM': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadLLM,
                    request_deserializer=unsloth__pb2.UnloadLLMRequest.FromString,
                    response_serializer=unsloth__pb2.UnloadLLMResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unsloth.UnslothModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('unsloth.UnslothModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UnslothModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/unsloth.UnslothModelService/Generate',
            unsloth__pb2.GenerateRequest.SerializeToString,
            unsloth__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unsloth.UnslothModelService/Init',
            unsloth__pb2.InitRequest.SerializeToString,
            unsloth__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadLLM(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/unsloth.UnslothModelService/UnloadLLM',
            unsloth__pb2.UnloadLLMRequest.SerializeToString,
            unsloth__pb2.UnloadLLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
