# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: unsloth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'unsloth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\runsloth.proto\x12\x07unsloth\"!\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"c\n\x10GenerateResponse\x12\x16\n\x0egenerated_text\x18\x01 \x01(\t\x12\x1a\n\x12input_tokens_count\x18\x02 \x01(\x05\x12\x1b\n\x13output_tokens_count\x18\x03 \x01(\x05\"\x1c\n\x0bInitRequest\x12\r\n\x05model\x18\x01 \x01(\t\"#\n\x0cInitResponse\x12\x13\n\x0binit_status\x18\x01 \x01(\x08\"\x12\n\x10UnloadLLMRequest\"#\n\x11UnloadLLMResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32\xd1\x01\n\x13UnslothModelService\x12\x41\n\x08Generate\x12\x18.unsloth.GenerateRequest\x1a\x19.unsloth.GenerateResponse0\x01\x12\x33\n\x04Init\x12\x14.unsloth.InitRequest\x1a\x15.unsloth.InitResponse\x12\x42\n\tUnloadLLM\x12\x19.unsloth.UnloadLLMRequest\x1a\x1a.unsloth.UnloadLLMResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'unsloth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=26
  _globals['_GENERATEREQUEST']._serialized_end=59
  _globals['_GENERATERESPONSE']._serialized_start=61
  _globals['_GENERATERESPONSE']._serialized_end=160
  _globals['_INITREQUEST']._serialized_start=162
  _globals['_INITREQUEST']._serialized_end=190
  _globals['_INITRESPONSE']._serialized_start=192
  _globals['_INITRESPONSE']._serialized_end=227
  _globals['_UNLOADLLMREQUEST']._serialized_start=229
  _globals['_UNLOADLLMREQUEST']._serialized_end=247
  _globals['_UNLOADLLMRESPONSE']._serialized_start=249
  _globals['_UNLOADLLMRESPONSE']._serialized_end=284
  _globals['_UNSLOTHMODELSERVICE']._serialized_start=287
  _globals['_UNSLOTHMODELSERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
